# GitHub Pages configuration
title: School Meals App
description: Система управления школьным питанием для 500+ школ
baseurl: ""
url: "https://fermiy100.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - README.md
  - node_modules
  - Gemfile
  - Gemfile.lock
  - backend/
  - .github/
  - .gitignore

# Include only necessary files
include:
  - _redirects

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
