[build]
  publish = "."
  command = "cd frontend && npm install && npm run build && cd .. && xcopy /E /Y frontend\\dist\\* ."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"