[build]
  command = "npm install && node server.js"
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_ENV = "production"
  JWT_SECRET = "your-super-secret-jwt-key-change-in-production"
  FRONTEND_URL = "https://fermiy100.github.io"