[providers]
node = "18.x"

[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "cp package-minimal.json package.json",
  "echo 'Using minimal package.json with no dependencies'"
]

[phases.build]
cmds = ["echo 'No build needed - minimal server'"]

[start]
cmd = "node server-minimal.js"
