[providers]
node = "18.x"

[phases.setup]
nixPkgs = ["nodejs_18"]
aptPkgs = []

[phases.install]
cmds = ["echo 'NO NPM - PURE NODE.JS SERVER'"]

[phases.build]
cmds = ["echo 'NO BUILD - STARTING DIRECTLY'"]

[start]
cmd = "node server-minimal.js"

[variables]
NPM_CONFIG_UPDATE_NOTIFIER = "false"
NO_UPDATE_NOTIFIER = "true"
